{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "trader-stack.fullname" . }}-api
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "trader-stack.fullname" . }}-api
  service:
    port: {{ .Values.service.apiPort }}
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        threshold: 99
      - name: request-duration
        threshold: 500
{{- end }}
