apiVersion: v1
kind: Service
metadata:
  name: trading-system-api
  labels:
    app: trading-system
spec:
  selector:
    app: trading-system
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  - name: dashboard
    port: 8501
    targetPort: 8501
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trading-system-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.trading-system.com
    - dashboard.trading-system.com
    secretName: trading-system-tls
  rules:
  - host: api.trading-system.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trading-system-api
            port:
              number: 5000
  - host: dashboard.trading-system.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trading-system-api
            port:
              number: 8501